### ISSUE TITLE
Compatibility With SherlockActionBar

### ISSUE THREAD

**Issue by patelakshay13890** [fredericojssilva/ShowTipsView#1]
Can we use this Showcase with ABS??
And can u provide code that has Backward Compatibility to API 8 or API 10 bcoz I do require in older model also...
Expecting +ve response..!!
 And thanx for sharing the code..

**Comment by fredericojssilva** [comment]
Yes you can use it with ABS.
I think that all the code will be compatible with API 8. Try to change the minSdkVersion on manifest, and let me know if something is not working. Today I have no time to do the tests.

**Comment by patelakshay13890** [comment]
Thanx for +ve reply,,.
And it has Backward Compatibility also..
Can't we access "Got It" button Click event in our app instead of its
static Click event in Library..?

**Comment by patelakshay13890** [comment]
?

**Comment by kanytu** [comment]
@patelakshay13890 there is a callback for the "got it" button: `showtips.setCallback`

Also the button has the Id `4375` so AFAIK you can find it and override it's click event.

**Comment by patelakshay13890** [comment]
Can you give an exampple??
Ane how we can show mulitple showcase in one activity at a time..?

**Comment by fredericojssilva** [comment]
@patelakshay13890 set the callback and relaunch another showtip.

.setCallback(new ShowTipsInterface(){
    @Override
    public void gotItClicked() {
    //Lunch new showtip
    }
});

**Comment by patelakshay13890** [comment]
Can you please send link or example for the same??
plz plz plz ....
