### ISSUE TITLE
setCallBack

### ISSUE THREAD

**Issue by patelakshay13890** [fredericojssilva/ShowTipsView#2]
why it is taking some duration when we call setCallBack to display another ShowTips?
plz reply fast..

**Comment by fredericojssilva** [comment]
are you setting some delay? ex: .setDelay(1000).

**Comment by patelakshay13890** [comment]
No i m not setting delay for call back but it's get call but  by delay..!!
U can also see that to show next tips on Got It it takes around 1 or 2
second to display another tips View.!!
so what could be the reason?

**Comment by patelakshay13890** [comment]
Got the problem solved..

**Comment by patelakshay13890** [comment]
but how can we saw tips on Sherlock Action Bar Menu & Menu Items..?
expecting +ve response
