### ISSUE TITLE
BackgroundColor with alpha / transparency

### ISSUE THREAD

**Issue by fakir22** [fredericojssilva/ShowTipsView#9]
Hello,

is there a way to make the backgroundColor() work with opacity ? 
I tried this on the ShowTipsView

```
setBackgroundColor(Color.parseColor("#99000000"))
```

but the background is still fully opaque.
I am doing it wrong ?

Thanks by advance.
Adrian

**Comment by fredericojssilva** [comment]
No, you are doing it right. I'm forcing the alpha value. 

I'll add a method to customize that. Let you know when it's done.

Thanks

**Comment by fredericojssilva** [comment]
@fakir22 solved, please get v1.0.3 and use setBackgroundAlpha

**Comment by fakir22** [comment]
Wow! Thank you! :)
